spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: scheduling
      auto-index-creation: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
